(defun char-list-to-int-list (l)
  (if (consp l)
      (cons (+ 1 (char-code (car l)) (- (char-code #\A)))
	    (char-list-to-int-list (cdr l)))
    nil))
  

(defun symbol-to-char-list (x)
  (char-list-to-int-list (coerce (symbol-name x) 'list)))

(defun hash-list (l)
  (if (consp l)
      (+ (car l)
	 (* 31 (hash-list (cdr l))))
    0))

(defun hash-symbol (x)
  (hash-list (symbol-to-char-list x)))

(defun set-nth (n l v)
  (if (zp n)
      (cons v (cdr l))
    (cons (car l)
	  (set-nth (1- n) (cdr l) v))))

(defconst *NBUCKETS* 30)

(defun dup (x n)
  (if (zp n)
      nil
    (cons x (dup x (1- n)))))

(defconst *EMPTY-HASH* (dup nil *NBUCKETS*))

(defun store (k v h)
  (let ((i (mod (hash-symbol k) *NBUCKETS*)))
    (set-nth i h (cons (cons k v) (nth i h)))))

(defun store-all (kvs h)
  (if (consp kvs)
      (store-all (cdr kvs)
		 (store (car (car kvs))
			(cdr (car kvs))
			h))
    (if (< (len h) 0)
	kvs
      h)))

(defconst *STATES* '((alabama . montgomery)
		     (alaska . juneau)
		     (arizona . phoenix)
		     (arkansas . little-rock)
		     (california . sacramento)
		     (colorado . denver)
		     (connecticut . hartford)
		     (delaware . dover)
		     (florida . tallahassee)
		     (georgia . atlanta)
		     (hawaii . honolulu)
		     (idaho . boise)
		     (illinois . springfield)
		     (indiana . indianapolis)
		     (iowa . des-moines)
		     (kansas . topeka)
		     (kentucky . frankfort)
		     (louisiana . baton-rouge)
		     (maine . augusta)
		     (maryland . annapolis)
		     (massachusetts . boston)
		     (michigan . lansing)
		     (minnesota . st-paul)
		     (mississippi . jackson)
		     (missouri . jefferson-city)
		     (montana . helena)
		     (nebraska . lincoln)
		     (nevada . carson-city)
		     (new-hampshire . concord)
		     (new-jersey . trenton)
		     (new-mexico . santa-fe)
		     (new-york . albany)
		     (north-carolina . raleigh)
		     (north-dakota . bismarck)
		     (ohio . columbus)
		     (oklahoma . oklahoma-city)
		     (oregon . salem)
		     (pennsylvania . harrisburg)
		     (rhode-island . providence)
		     (south-carolina . columbia)
		     (south-dakota . pierre)
		     (tennessee . nashville)
		     (texas . austin)
		     (utah . salt-lake-city)
		     (vermont . montpelier)
		     (virginia . richmond)
		     (washington . olympia)
		     (west-virginia . charleston)
		     (wisconsin . madison)
		     (wyoming . cheyenne))) 


(hash-symbol 'alabama)
